### ISSUE TITLE
Prevent duplicate webhooks

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/topcoder-x-ui#133]
When creating the webhooks, we don't do anything to prevent a user from adding the webhooks from the UI to a repository more than once, but if a duplicate is added, it breaks a lot of things in TC-X.  We need to ensure that a user can't add the same webhook multiple times.  If the user clicks `Add Webhook`, and a webhook already exists, we should *replace* the existing webhook with a new one, not add one.

This will apply to both Github and Gitlab.

**Comment by afrisalyp** [comment]
Hi, please clarify my understanding of this issue.
If the user clicks `Add Webhook`, a webhook URL, for example, 

http://x.topcoder-dev.com/webhooks/gitlab

will be put on Gitlab as the project's webhook.

If the user clicks it again, the same webhook URL should not be stored on Gitlab. Is it correct?

But what happens if the new webhook URL is different from the stored webhook URL on Gitlab/Github?

> If the user clicks Add Webhook, and a webhook already exists, we should replace the existing webhook with a new one, not add one.

The desc mentions that we should replace the old with the new.
But there is some point to note that Gitlab/Github allows multiple webhook and the user can add them directly from the website. 
Should we delete all the webhooks and replace with the new one?

**Comment by jmgasper** [comment]
Can we just delete the webhooks that reference topcoder-x-receiver?

**Comment by afrisalyp** [comment]
Yes, I think it's possible and the best solution.

**Comment by anonymousjaggu** [comment]
> Can we just delete the webhooks that reference topcoder-x-receiver?

@jmgasper What do you mean here by this, since we don't have any other place than the `topcoder-x-receiver` to use webhook
