### ISSUE TITLE
Allow copilots to cancel a ticket

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/topcoder-x-ui#135]
We've all faced the issue when the challenge API just doesn't want to work properly and we end up paying the member manually while still having the tcx ticket open and kinda stuck.

It would be great to be able to just cancel a ticket either from x.topcoder.com or by setting a specific tcx ticket.

**Comment by jmgasper** [comment]
@ThomasKranitsas - We are a bit stuck here as well due to the API.  I'd like to be able to delete the challenge, but unfortunately that's not possible in the API.  The other option is to *activate* the challenge and then cancel it, but:

1.  I don't want to do any sort of activation due to billing and other issues
2. Even if we did activate, the project doesn't "start" right away due to weird issues with the auto-scheduler, so we'd have to poll it for potentially multiple hours before we could then cancel it.

What we'll do is allow the copilot to clear out the DB record and redo the processor / challenge creation step.  Hopefully that will mitigate the challenge API issues a bit. (https://github.com/topcoder-platform/topcoder-x-ui/issues/127)

I've also been working on moving from the v3 challenge API to v4, which seems a little more stable / faster.  This has been taking much longer than expected for a variety of reasons.  🤦‍♂
