### ISSUE TITLE
Do away with labels

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/topcoder-x-ui#321]
My (CoPilot) objective is to pay members out for their work on tasks / tickets / issues.
With this context, I am not sure of the purpose of having multiple labels that TCX responds to. The labels, if any, should be the prerogative of the copilot on how they wish to manage their project (I understand the need to standardize the labels across bug bashes but my complain is more about TCX being interested in all of them / reacting to all of them).

Right now, TCX needs 3 labels at minimum:
- `tcx_OpenForPickup` which will create the contest
- `tcx_Assigned` which will update the assignee for the contest
- `tcx_FixAccepted` which will determine if the member gets paid out not

and a ticket close event which actually pays the member out.

Instead, I believe TCX should respond to just 1 command (think gitlab commands) or 1 label that will determine if the member gets paid or not. And that 1 label should be the only event that TCX should respond to.

My current experience with TCX is not that great. It sometimes will update the ticket within seconds on whether the action succeeded (contest created / contest updated with member etc) and sometimes will take ages. Sometimes nothing will happen and you are not sure if you can proceed with the next steps... forcing you to redo the previous steps and figure out what you did wrong...

I want to pay the member out. TCX should not really pay attention to whether the open for pickup or assigned labels are set. When its time to pay the member out, I want to let TCX know, and at this moment, it should create the contest, assign the member and activate it. It should not, early on, create the contest, update the assignee as and when members assign or unassign themselves and just clutter the thread with its messages. Just 1 event should be enough for TCX to pay the member out.

**Comment by jmgasper** [comment]
@cwdcwd / @rootelement ☝️  Let me know your thoughts on this.  

The move to the v5 API will fix up the delays / inconsistencies noted, which all stem from the challenge API. 

Part of why we do the "longer" process now is that, in theory, it allows the PM to better manage the budget flow of the project since the challenges are created and assigned payment earlier.  If that's not an issue, we can start to delay the challenge creation / assigning until the end of a ticket.

**Comment by rootelement** [comment]
I disagree with @callmekatootie here a little bit. If your only thing you want to do is pay out a member, we have payment.topcoder.com. If it's tied to work, we (as architects at topcoder specifically) are always charged with "pipeline". The last project I ran as an architect before i moved to the Prod Dev team, I had to put all my expected challenges and tasks into direct to gameplan out the work so that the management team could see the forecast of work on the horizon. So i think there's still the need to have some sort of "this issue is tied to dollars and will be paid out when it's closed".

All that being said, Justin is right that a lot of the labels now are because of the v3/v4 api, and the fail/retry nature of that API, and its very long delays. As we move over to v5, this will be remedied to a certain degree (although v5 still does call v4, but it takes the responsibility off of the caller - TCX).

@jmgasper will be evaluating TCX as v5 becomes production ready. I think we can evaluate this issue at that time and consider the flow. Also, we have to consider that against gitlab/github, as well as other things we can integrate into TCX, such as DevOps and Jira.
