### ISSUE TITLE
Duplicate created when reopening

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/topcoder-x-ui#391]
Interesting bug in TCX today:

1. Created an issue with a title/price and added label OpenForPickup
2. I added you as the assignee
3. I closed the issue without adding Fix Accepted
4. TCX said it wasn’t paid out because the Fix Accepted label wasn’t added
5. I reopened it, Added the Fix Accepted Issue, and Closed it (pretty quickly)
6. TCX created a new issue
7. I reopened the issue, removed Fix Accepted, Re-added Fix Accepted, Closed it.
8. It closed the 2nd issue. 1st issue is still in draft

**Comment by anonymousjaggu** [comment]
@jmgasper I have also faced this issue 

https://user-images.githubusercontent.com/31332424/113913363-f6e94400-97fb-11eb-82f2-ab51d238bad8.mp4

**Comment by afrisalyp** [comment]
@jmgasper 

When we close an issue without `tcx_FixAccepted`, we'll update the challenge with `Canceled` status.
And we won't use the record again if we re-open the issue. So that's why topcoder-x will create a new challenge.
That's the current behaviour.

There are three conditions that lead to the cancellation process after closing an issue:

1. The issue has no `tcx_FixAccepted`.
2. No price or the price is 0.
3. The issue has `tcx_Canceled` label.

What should we do to fix this issue?

**Comment by jmgasper** [comment]
Can we remove condition #1?

**Comment by afrisalyp** [comment]
@jmgasper 

Sure. Thanks.
