### ISSUE TITLE
Introduce a new label to prepare a ticket

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/topcoder-x-ui#96]
When adding the `tcx_OpenForPickup` label, members will try to grab the ticket as soon as they can but the challenge for this ticket may not have been created yet which will cause upcoming actions to fail.

We can add a `tcx_Prepare` (or similar) ticket that will tell the processor to setup the challenge for the ticket and once ready, it'll add the `tcx_OpenForPickup` ticket so people can start working on the ticket.

**Comment by jmgasper** [comment]
@ThomasKranitsas - I'll try to fix the processor so that the events wait for challenge creation and then complete successfully.  That *should* be happening now, but it sounds like it's not - do you have an example or two you can share?

Alternatively, I think you should be able to apply a prize, but no label and the challenge should still get created, at which point you can apply the label.

**Comment by ThomasKranitsas** [comment]
Yeah, applying the prize and waiting for the challenge to be created before adding the `tcx_OpenForPickup` label works but I still have to keep an eye to see when the challenge is ready to be opened for pickup.

The pseudo code for my suggestion would be something like this:

```
on 'titleUpdated':
	if challengeExists:
		updatePrize();

on 'tcx_Prepare':
	if !challengeExists:
		createChallenge(prize: parsePrize() || 0);
		openForPickup();
```

This should do what you suggested (add prize > wait for the challenge > open for pickup) automatically, no?

**Comment by jmgasper** [comment]
We've added `tcx_NotReady` as a placeholder.  This is just in dev, not prod yet.
